name: device_session_id
description: This is a package that uses the Openpay iOS and Openpay Android libraries to get the Device Session ID for the anti-fraud system.
version: 1.0.4
homepage: https://github.com/FMarcelFC
repository: https://github.com/FMarcelFC/device_session_id

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.device_session_id
        pluginClass: DeviceSessionIdPlugin
      ios:
        pluginClass: DeviceSessionIdPlugin


